import { Inter } from "next/font/google";
import "./globals.css";
import HeaderPage from "@/components/header/header";
import { SubformLoginProvider } from "@/components/context/subformLoginContext";
import { AuthProvider } from "@/components/context/authContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <AuthProvider>
            <SubformLoginProvider>

            
            <HeaderPage></HeaderPage>
            
            <div className="container mx-auto px-36 bg-white h-screen">
            {children}
            </div>
            </SubformLoginProvider>
          </AuthProvider>
        
        
        
        </body>
    </html>
  );
}

